### ISSUE TITLE
[Python3] `TypeError: expected string or bytes-like object`

### ISSUE THREAD

**Issue by takano32** [tinbotu/sub#111]
発生しがちエラー

```
Traceback (most recent call last):
  File "/var/www/cgi-bin/sub/sun.cgi", line 1540, in <module>
    no.say(slack=no.is_slack, lingr=False)
  File "/var/www/cgi-bin/sub/sun.cgi", line 1520, in say
    resp = "\n".join(tuple(self.response())).rstrip("\n")
  File "/var/www/cgi-bin/sub/sun.cgi", line 1490, in response
    if pattern.search(text):
TypeError: expected string or bytes-like object
```

#110 がマージされたら型ヒントで消す。

**Comment by takano32** [comment]
修正を入れた。

https://github.com/tinbotu/sub/commit/d42df577bd6724ff32f097f9aae0002a260d138c

参考

https://stackoverflow.com/questions/43727583/

**Comment by takano32** [comment]
格納するときに `str` に変換するようにした。

https://github.com/tinbotu/sub/commit/7abe0786fb020e03fe4d5e67709223c0a6e7f90d
